export class UtilsServiceGameTags {
    public static readonly FFAHeaderConfigsStrings: string[] = [
        "GAME_FFA_MAP", "GAME_FFA_DISASTERS",
        "GAME_FFA_BONUS_RESOURCES", "GAME_FFA_STRATEGIC_RESOURCES",
        "GAME_FFA_WONDERS", "GAME_FFA_AGE",
        "GAME_FFA_GOLD_TRADING", "GAME_FFA_STRATEGIC_TRADING",
        "GAME_FFA_FRIENDS", "GAME_FFA_MILITARY_ALLIANCE",
        "GAME_FFA_CHATTING", "GAME_FFA_DRAFT"
    ];

    public static readonly FFAOptionsConfigsStrings: string[][] = [
        [
            "GAME_FFA_MAP_PANGAEA", "GAME_FFA_MAP_CONTINENTS",
            "GAME_FFA_MAP_HIGHLANDS", "GAME_FFA_MAP_SEVEN_SEAS",
            "GAME_FFA_MAP_LAKES", "GAME_FFA_MAP_ARCHIPELAGO",
            "GAME_FFA_MAP_INLAND_SEA", "GAME_FFA_MAP_FRACTAL",
            "GAME_FFA_MAP_CONTINENTS_AND_ISLANDS", "GAME_FFA_MAP_PRIMORDIAL",
            "GAME_FFA_MAP_TILTED_AXIS",
        ],
        [
            "GAME_FFA_DISASTERS_1", "GAME_FFA_DISASTERS_2",
            "GAME_FFA_DISASTERS_3", "GAME_FFA_DISASTERS_4"
        ],
        [
            "GAME_FFA_BONUS_RESOURCES_STANDARD", "GAME_FFA_BONUS_RESOURCES_ABUNDANT"
        ],
        [
            "GAME_FFA_STRATEGIC_RESOURCES_STANDARD", "GAME_FFA_STRATEGIC_RESOURCES_ABUNDANT",
            "GAME_FFA_STRATEGIC_RESOURCES_GUARANTEED"
        ],
        [
            "GAME_FFA_WONDERS_STANDARD", "GAME_FFA_WONDERS_ABUNDANT"
        ],
        [
            "GAME_FFA_AGE_STANDARD", "GAME_FFA_AGE_NEW"
        ],
        [
            "GAME_FFA_GOLD_TRADING_NO", "GAME_FFA_GOLD_TRADING_ALLIES",
            "GAME_FFA_GOLD_TRADING_FRIENDS", "GAME_FFA_GOLD_TRADING_YES"
        ],
        [
            "GAME_FFA_STRATEGIC_TRADING_NO", "GAME_FFA_STRATEGIC_TRADING_ALLIES",
            "GAME_FFA_STRATEGIC_TRADING_FRIENDS", "GAME_FFA_STRATEGIC_TRADING_YES"
        ],
        [
            "GAME_FFA_FRIENDS_0", "GAME_FFA_FRIENDS_1",
            "GAME_FFA_FRIENDS_2", "GAME_FFA_FRIENDS_3",
            "GAME_FFA_FRIENDS_INFINITY"
        ],
        [
            "GAME_FFA_MILITARY_ALLIANCE_NO", "GAME_FFA_MILITARY_ALLIANCE_YES"
        ],
        [
            "GAME_FFA_CHATTING_ANY", "GAME_FFA_CHATTING_PUBLIC"
        ],
        [
            "GAME_FFA_DRAFT_CLASSIC", "GAME_FFA_DRAFT_BLIND"
        ]
    ];

    public static readonly teamersHeaderConfigsStrings: string[] = [
        "GAME_TEAMERS_MAP", "GAME_TEAMERS_DISASTERS",
        "GAME_TEAMERS_BONUS_RESOURCES", "GAME_TEAMERS_STRATEGIC_RESOURCES",
        "GAME_TEAMERS_WONDERS", "GAME_TEAMERS_AGE",
        "GAME_TEAMERS_RELIC", "GAME_TEAMERS_REMAPS",
        "GAME_TEAMERS_SPLIT"
    ];

    public static readonly teamersOptionsConfigsStrings: string[][] = [
        [
            "GAME_TEAMERS_MAP_PANGAEA", "GAME_TEAMERS_MAP_CONTINENTS",
            "GAME_TEAMERS_MAP_HIGHLANDS", "GAME_TEAMERS_MAP_SEVEN_SEAS",
            "GAME_TEAMERS_MAP_LAKES", "GAME_TEAMERS_MAP_ARCHIPELAGO",
            "GAME_TEAMERS_MAP_INLAND_SEA", "GAME_TEAMERS_MAP_FRACTAL",
            "GAME_TEAMERS_MAP_CONTINENTS_AND_ISLANDS", "GAME_TEAMERS_MAP_TILTED_AXIS",
            "GAME_TEAMERS_MAP_PRIMORDIAL"
        ],
        [
            "GAME_TEAMERS_DISASTERS_1", "GAME_TEAMERS_DISASTERS_2",
            "GAME_TEAMERS_DISASTERS_3", "GAME_TEAMERS_DISASTERS_4"
        ],
        [
            "GAME_TEAMERS_BONUS_RESOURCES_STANDARD", "GAME_TEAMERS_BONUS_RESOURCES_ABUNDANT"
        ],
        [
            "GAME_TEAMERS_STRATEGIC_RESOURCES_STANDARD", "GAME_TEAMERS_STRATEGIC_RESOURCES_ABUNDANT",
            "GAME_TEAMERS_STRATEGIC_RESOURCES_GUARANTEED"
        ],
        [
            "GAME_TEAMERS_WONDERS_STANDARD", "GAME_TEAMERS_WONDERS_ABUNDANT"
        ],
        [
            "GAME_TEAMERS_AGE_STANDARD", "GAME_TEAMERS_AGE_NEW"
        ],
        [
            "GAME_TEAMERS_RELIC_TURN_20", "GAME_TEAMERS_RELIC_YES"
        ],
        [
            "GAME_TEAMERS_REMAPS_NO", "GAME_TEAMERS_REMAPS_YES"
        ],
        [
            "GAME_TEAMERS_SPLIT_CLASSIC", "GAME_TEAMERS_SPLIT_DOUBLE",
            "GAME_TEAMERS_SPLIT_CWC", "GAME_TEAMERS_SPLIT_RANDOM"
        ]
    ];
}
